### ISSUE TITLE
Anyfile Notepad leaves "Anyfile Notepad Files" directories in my Google Drive root directory

### ISSUE THREAD

**Issue by PioKub** [julsemaan/anyfile-notepad#13]
Anyfile Notepad leaves "Anyfile Notepad Files" directories in my Google Drive root directory. These directories are created when I open text files, one directory per each file. I presume these are some sort of "temp" directories. The problem is that they are created in the root directory of my Google drive and that they are not deleted after I close the edited files.

**Comment by julsemaan** [comment]
There should be a single directory created by the app. This is a new requirement for the app to be in gsuite marketplace where the files this app creates are in that folder by default. 

Are you saying there are multiple folders named like this ?

**Comment by PioKub** [comment]
OK, but this folder should be removed after I close the file(s) / application, so that the root directory is not cluttered, right?
Until recently, there were multiple instances of this folder created, for example, when I opened and closed 3 text files, there would be 3 folders of the same name created in the root directory. However, I have just tested this now and this issue seems to be gone - has this been fixed recently?

**Comment by julsemaan** [comment]
This folders stores the files you create via the app. This means that if you create a new file without specifying a directory, this is where it will end up. Since these files are expected to be persistent (you wouldn't want the file you created via the app to be deleted), then it needs to stay.

There wasn't any fix to prevent the creation of multiple folders, it should have always checked the existence of the folder before attempting to create another one. If the multi-folder issue happens again, let me know how you replicate it and I'll look into it.

I'll close this issue for now, reopen if it needs more attention
